<a href="https://colab.research.google.com/github/lakkireddylahari-bot/data-science-learning/blob/main/knnclassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

In [36]:
df = pd.read_csv("/content/drive/MyDrive/knnclassification.csv")

In [37]:
df

,ApplicantIncome,CreditScore,LoanAmount,EmploymentYears,ExistingLoans,Loan_Status
0,61907,739,151745,19,1,Approved
1,25495,521,607311,2,4,Rejected
2,98010,798,662453,11,0,Approved
3,101378,657,436907,16,1,Approved
4,73393,710,446418,12,1,Approved
...,...,...,...,...,...,...
4995,101851,850,455642,7,2,Approved
4996,64105,668,679590,7,2,Rejected
4997,87942,660,218558,19,2,Approved
4998,62637,613,853761,2,2,Rejected
4999,28644,638,504750,4,3,Rejected

In [38]:
df.head()

,ApplicantIncome,CreditScore,LoanAmount,EmploymentYears,ExistingLoans,Loan_Status
0,61907,739,151745,19,1,Approved
1,25495,521,607311,2,4,Rejected
2,98010,798,662453,11,0,Approved
3,101378,657,436907,16,1,Approved
4,73393,710,446418,12,1,Approved

In [39]:
df.columns

Index(['ApplicantIncome', 'CreditScore', 'LoanAmount', 'EmploymentYears',
       'ExistingLoans', 'Loan_Status'],
      dtype='object')

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ApplicantIncome  5000 non-null   int64
 1   CreditScore      5000 non-null   int64
 2   LoanAmount       5000 non-null   int64
 3   EmploymentYears  5000 non-null   int64
 4   ExistingLoans    5000 non-null   int64
 5   Loan_Status      5000 non-null   object
dtypes: int64(5), object(1)
memory usage: 234.5+ KB

In [41]:
df.isnull().sum()

ApplicantIncome    0
CreditScore        0
LoanAmount         0
EmploymentYears    0
ExistingLoans      0
Loan_Status        0
dtype: int64

In [42]:
df.duplicated().sum()

np.int64(0)

In [44]:
X = df.drop("Loan_Status", axis = 1)
X
Y = df["Loan_Status"]

In [45]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=42
)

In [46]:
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(4000, 5)
(1000, 5)
(4000,)
(1000,)

In [48]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [49]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, Y_train)

KNeighborsClassifier()

In [50]:
y_pred = knn.predict(X_test)

In [51]:
confusion_matrix = confusion_matrix(Y_test, y_pred)
print(confusion_matrix)
accuracy = accuracy_score(Y_test, y_pred)
print(accuracy)
precision = precision_score(Y_test, y_pred,pos_label ="Approved")
print(precision)
recall = recall_score(Y_test, y_pred,pos_label ="Approved")
print(recall)
f1 = f1_score(Y_test, y_pred,pos_label ="Approved")
print(f1)

[[500   1]
 [  0 499]]
0.999
1.0
0.998003992015968
0.999000999000999